return{
    feature="Global",
    guide={
        "这是bot的配置文件",
        "你可以配制bot账号,所用端口,一些功能是否使用等等",
        "请按照注释填写配置文件",
        "对于功能与游戏的设置,请在列表内输入使用该功能的群号,用英文逗号分割,如果某一功能是整个号中任何群聊都适用,请写true,若都不适用,则写false或者空列表;空列表在运行时可更改,而false将不会注册监听器",
        "首先填写bot的账号等基础配置",
        "请在port处填写端口(任意空闲端口均可),id处填写QQ号,useGuide处填写是否开启配置文件中的注释(true为开启,false为关闭),log处填写是否使用日志,是写明存储日志的路径，否写null或不填",
    },
    help=nil,
    config={
        {name="port",type={"java.lang.Integer"},nullable=false},
        {name="id",type={"java.lang.Long"},nullable=false},
        {name="useGuide",type={"java.lang.Boolean"},nullable=false},
        {name="log",type={"java.lang.String"},nullable=true},
    }
}