plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.6.1'
    id 'org.jetbrains.kotlin.jvm' version '2.3.20'
}
java{
    toolchain {
        JavaLanguageVersion.of(17)
    }
}

group 'io.github.et'
version '5.2.8'

repositories {
    mavenCentral()
}

tasks.withType(JavaCompile){
    options.encoding='UTF-8'
    options.annotationProcessorPath = configurations.annotationProcessor
}

shadowJar{
    manifest.attributes.put("Main-Class",'io.github.et.Main')
}

dependencies {
    implementation 'com.alibaba:fastjson:2.0.62'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.3.20'
    implementation "top.mrxiaom.mirai:overflow-core:1.1.0"
    implementation 'net.mamoe:mirai-core:2.16.0'
    implementation 'org.luaj:luaj-jse:3.0.1'
    compileOnly 'org.projectlombok:lombok:1.18.46'
    annotationProcessor 'org.projectlombok:lombok:1.18.46'
    implementation("io.github.enderman-tping:Conopt4j:1.0.1")

}

sourceSets {
    main.kotlin.srcDirs += 'src/main/kotlin'
    main.java.srcDirs += 'src/main/java'
}

test {
    useJUnitPlatform()
}
