package io.github.et.games.iAmAWolf

enum class Status {
    PRE_GAME,GETTING_READY,ENGAGING,WOLF,DOUBLE_CLAW,INVISIBLE_WOLF,GARGOYLE,WOLF_KING,WHITE_WOLF_KING,VILLAGER,GUARDIAN,WITCH,PREDICTOR,FOOL,HUNTER,KNIGHT,DAY,POLICE
}