conopt4j.logger.level = Level.DEBUG
conopt4j.logger.info = Color.WHITE
conopt4j.logger.warn = Color.YELLOW
conopt4j.logger.debug = Color.CYAN
conopt4j.logger.error = Color.RED
conopt4j.logger.fatal = Color.PURPLE
conopt4j.logger.severe = Color.RED
conopt4j.logger.fine = Color.BLUE
conopt4j.logger.useDate = true
conopt4j.logger.useTrace = true
conopt4j.logger.output =
conopt4j.logger.maxHistory = 1024
conopt4j.monitor.use = true
conopt4j.status.interval = 500
conopt4j.command.prompt = >